'use client'
import React, { useEffect, useState } from 'react'
import { List } from 'lucide-react'

interface TocHeading {
  id: string
  text: string
  level: number
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '')
}

/** Parse h2/h3 headings from raw markdown (matches the IDs generated by MarkdownRenderer). */
function extractHeadings(markdown: string): TocHeading[] {
  const headings: TocHeading[] = []
  const lines = markdown.split('\n')

  for (const line of lines) {
    // Skip code blocks
    if (line.startsWith('```')) continue

    const match = line.match(/^(#{2,3})\s+(.+)$/)
    if (match) {
      const level = match[1].length
      const raw = match[2].replace(/[*_`~\[\]]/g, '').trim()
      headings.push({ id: slugify(raw), text: raw, level })
    }
  }

  return headings
}

export default function TableOfContents({ markdown }: { markdown: string }) {
  const headings = extractHeadings(markdown)
  const [activeId, setActiveId] = useState<string>('')
  const [isOpen, setIsOpen] = useState(false)

  useEffect(() => {
    if (headings.length === 0) return

    const observer = new IntersectionObserver(
      (entries) => {
        // Find the first heading that is intersecting
        const visible = entries.filter((e) => e.isIntersecting)
        if (visible.length > 0) {
          setActiveId(visible[0].target.id)
        }
      },
      { rootMargin: '-80px 0px -60% 0px', threshold: 0 },
    )

    for (const { id } of headings) {
      const el = document.getElementById(id)
      if (el) observer.observe(el)
    }

    return () => observer.disconnect()
  }, [headings])

  if (headings.length < 3) return null

  return (
    <>
      {/* Mobile toggle */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="xl:hidden flex items-center gap-2 mb-4 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-slate-800 rounded-lg hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
        aria-expanded={isOpen}
      >
        <List className="w-4 h-4" />
        Table of Contents
      </button>

      {/* TOC panel – always visible on xl, toggle on smaller */}
      <nav
        aria-label="Table of contents"
        className={`${
          isOpen ? 'block' : 'hidden'
        } xl:block xl:sticky xl:top-24 xl:max-h-[calc(100vh-8rem)] xl:overflow-y-auto rounded-xl bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 p-4 mb-6 xl:mb-0`}
      >
        <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-500 dark:text-gray-400 mb-3">
          On this page
        </h2>
        <ul className="space-y-1 text-sm">
          {headings.map((h) => (
            <li key={h.id} style={{ paddingLeft: `${(h.level - 2) * 0.75}rem` }}>
              <a
                href={`#${h.id}`}
                onClick={() => setIsOpen(false)}
                className={`block py-1 leading-snug transition-colors duration-150 ${
                  activeId === h.id
                    ? 'text-primary-600 dark:text-primary-400 font-medium'
                    : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200'
                }`}
              >
                {h.text}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </>
  )
}
